In [4]:
import torch

In [5]:
import time

import pandas as pd
import numpy as np
import os
import logging
import sys
sys.path.append("/home/zjh/remote/mrbert/V1/")
import torch

In [6]:
lth = {

    "FreeSolv":642,
    "bace":1513,
    "LogS":5045,
    "Lipophilicity":4200,
    "ESOL":1128,
    "Ames":6719,
    "BBBP":2039,

}
task_type = {
    "FreeSolv":"regression",
    "bace":"classify",
    "LogS":"regression",
    "Lipophilicity":"regression",
    "ESOL":"regression",
    "Ames":"classify",
    "BBBP":"classify",

}

In [7]:
res_dir = "/home/zjh/mr/res/V1"
res = {}
for fn in os.listdir(res_dir):
    if fn.endswith("csv"):
        v = pd.read_csv(os.path.join(res_dir,fn))["best_metric"].values
        epoch = v = pd.read_csv(os.path.join(res_dir,fn))["best_epoch"].values
        print(epoch)
        res[fn.split(".")[0]] = float(v)
direct = res

[12]
[19]
[11]
[15]
[5]
[9]
[10]


In [8]:
# res_dir = "/home/zjh/mr/res_pretrain/V1_fine"
# res = {}
# for fn in os.listdir(res_dir):
#     if fn.endswith("csv"):
#         v = pd.read_csv(os.path.join(res_dir,fn))["best_metric"].values
#         res[fn.split(".")[0]] = float(v)
# fine = res


In [9]:
fine = {"FreeSolv":0.942305,
 "bace":0.857118,

"LogS":0.819316,
"Lipophilicity":0.682633,
"ESOL":0.876687,
"Ames":0.867142,
"BBBP":0.910858
 }

In [10]:
mg_fine = {"FreeSolv":0.8463,
 "bace":0.8868,

"LogS":0.8766,
"Lipophilicity":0.7650,
"ESOL":0.8474,
"Ames":0.8933,
"BBBP":0.9208,
 }

In [11]:
comp = pd.DataFrame({"direct":direct,"fine":fine,"mg_fine":mg_fine,"lth":lth,"task_type":task_type})
comp["improve%"] = (comp["fine"] - comp["direct"]) / comp["direct"] * 100
comp

direct      fine  mg_fine   lth   task_type   improve%
FreeSolv         12.0  0.942305   0.8463   642  regression -92.147458
bace             19.0  0.857118   0.8868  1513    classify -95.488853
LogS             11.0  0.819316   0.8766  5045  regression -92.551673
Lipophilicity    15.0  0.682633   0.7650  4200  regression -95.449113
ESOL              5.0  0.876687   0.8474  1128  regression -82.466260
Ames              9.0  0.867142   0.8933  6719    classify -90.365089
BBBP             10.0  0.910858   0.9208  2039    classify -90.891420

In [12]:
from tqdm import tqdm

In [13]:
import time
a = time.time()

In [14]:
b = time.time()

In [15]:
b - a

0.34261608123779297

In [16]:
a,b = [1,2]

In [19]:
d = torch.load("/home/zjh/mr/pretrain/dataset/0-10000_test.pth")

In [21]:
_,_,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = data[1]

In [31]:
torch.sum(torsion_k == torsion_k)

tensor(214)

In [33]:
if torch.sum(torsion_k == torsion_k):
    print("t")

t


In [25]:
torsion_t

tensor([32,  2, 32,  2, 32,  2,  3, 42,  3, 42,  4, 26,  4, 26,  5, 43,  5, 43,
         6, 25,  6, 25,  7,  7,  8, 44,  9, 10,  9, 10, 25, 11, 25, 11, 12, 45,
        12, 45, 17, 13, 17, 13, 14, 46, 14, 46, 15, 47, 15, 47, 16, 48, 16, 48,
        17, 49, 17, 49, 18, 12, 18, 12, 19, 20, 21, 19, 20, 21, 50, 22, 24, 50,
        22, 24, 50, 22, 24, 51, 52, 23, 51, 52, 23, 51, 52, 23, 53, 24, 54, 53,
        24, 54, 53, 24, 54, 21, 55, 56, 21, 55, 56, 21, 55, 56,  5,  5, 27, 31,
        27, 31, 28, 28, 57, 29, 30, 58, 59, 60, 58, 59, 60, 58, 59, 60, 62, 61,
        63, 62, 61, 63, 62, 61, 63, 32, 64, 32, 64, 33,  1, 33,  1, 65, 34, 38,
        65, 34, 38, 67, 35, 66, 67, 35, 66, 67, 35, 66, 36, 69, 68, 36, 69, 68,
        36, 69, 68, 37, 70, 37, 70, 37, 70, 38, 71, 72, 38, 71, 72, 33, 73, 74,
        33, 73, 74, 33, 73, 74,  0,  2,  0,  2, 32, 65, 34, 32, 65, 34, 32, 65,
        34,  4,  6, 11, 13, 11, 13, 18, 50, 22, 18, 50, 22, 18, 50, 22],
       dtype=torch.uint8)

In [23]:
for row in data:
    _,_,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = row
    if (torsion_k==torsion_i):
        print("t1")
    if (torsion_k == torsion_j):
        print("t2")
    if (torsion_k == torsion_t):
        print("t3"
              )
    if (torsion_i == torsion_j):
        print("t4")
    if (torsion_t == torsion_j):
        print("t5")
    if (torsion_t == torsion_i):
        print("t6")

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [36]:
base_dir = "/home/zjh/mr/pretrain/dataset"

for i in range(0,49):
    print(i)
    start = time.time()
    fn = str(i*10000)+"-"+str((i+1)*10000)+"_test.pth"
    data = torch.load(os.path.join(base_dir,fn))
    for row in data:
        _,_,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = row
        if (torch.sum(torsion_k==torsion_i)):
            print("t1")
        if torch.sum(torsion_k == torsion_j):
            print("t2")
        if torch.sum(torsion_k == torsion_t):
            print("t3"
                  )
        if torch.sum(torsion_i == torsion_j):
            print("t4")
        if torch.sum(torsion_t == torsion_j):
            print("t5")
        if torch.sum(torsion_t == torsion_i):
            print("t6")



0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48


In [13]:
def pro(data):
    new_data = []
    for row in tqdm(iter(data),total=len(data)):
        smiles = row[0]
        nmr = row[1]
        pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = [d for d in row[2:]]
        if (len(pos) > 255):
            print(len(pos))
            continue
        if (len(dist)==0 or len(angle)==0 or len(torsion)==0):
            print("valid")
            continue
        new_data.append([smiles,torch.tensor(nmr),pos,dist_i.byte(),dist_j.byte(),dist,angle_i.byte(),angle_j.byte(),angle_k.byte(),angle,torsion_k.byte(),torsion_i.byte(),torsion_j.byte(),torsion_t.byte(),
                         torsion])
    return new_data
base_dir = "/home/zjh/mr/pretrain/dataset"
for i in range(1,10):
    print(i)
    fn = str(i*10000)+"-"+str((i+1)*10000)+".pth"
    fn_prefix = str(i*10000)+"-"+str((i+1)*10000)
    data = torch.load(os.path.join(base_dir,fn))
    new_data = pro(data)
    torch.save(new_data,os.path.join(base_dir,fn_prefix+"_test.pth"))


1


 10%|▉         | 953/9996 [00:00<00:03, 2987.12it/s]

valid


 45%|████▌     | 4530/9996 [00:01<00:01, 3675.49it/s]

valid


 59%|█████▉    | 5911/9996 [00:01<00:01, 3694.71it/s]

valid
valid


 83%|████████▎ | 8291/9996 [00:02<00:00, 5701.62it/s]

valid
valid


100%|██████████| 9996/9996 [00:02<00:00, 4049.45it/s]

valid
valid


2


 20%|██        | 2028/9995 [00:00<00:01, 4010.17it/s]

valid
valid
valid


 48%|████▊     | 4823/9995 [00:01<00:00, 5446.83it/s]

valid
valid


 76%|███████▌  | 7613/9995 [00:01<00:00, 6355.72it/s]

valid
valid
valid


 94%|█████████▍| 9383/9995 [00:02<00:00, 4932.41it/s]

valid


100%|██████████| 9995/9995 [00:02<00:00, 4566.69it/s]


3


 11%|█▏        | 1148/9994 [00:00<00:03, 2590.65it/s]

valid
valid


 38%|███▊      | 3809/9994 [00:01<00:01, 4186.82it/s]

valid
valid
valid


 55%|█████▍    | 5493/9994 [00:01<00:01, 3638.87it/s]

valid
valid
valid


 62%|██████▏   | 6230/9994 [00:01<00:01, 3452.57it/s]

valid
valid


 75%|███████▍  | 7465/9994 [00:02<00:00, 3811.08it/s]

valid


 79%|███████▊  | 7851/9994 [00:04<00:03, 568.44it/s] 

valid
valid


 93%|█████████▎| 9310/9994 [00:04<00:00, 1509.62it/s]

valid


100%|██████████| 9994/9994 [00:04<00:00, 2022.79it/s]


4


 15%|█▍        | 1497/9996 [00:00<00:02, 4155.86it/s]

valid
valid
valid


 40%|████      | 4020/9996 [00:01<00:01, 4283.19it/s]

272
valid


 49%|████▊     | 4858/9996 [00:01<00:01, 3652.74it/s]

valid


 75%|███████▌  | 7540/9996 [00:02<00:00, 3659.09it/s]

valid


100%|██████████| 9996/9996 [00:02<00:00, 3754.21it/s]


5


 12%|█▏        | 1207/9997 [00:00<00:02, 3058.61it/s]

valid


 21%|██▏       | 2140/9997 [00:00<00:02, 2807.73it/s]

valid


 32%|███▏      | 3163/9997 [00:01<00:02, 3175.67it/s]

valid
valid


 50%|████▉     | 4985/9997 [00:01<00:01, 4164.63it/s]

valid
valid


 70%|███████   | 7025/9997 [00:01<00:00, 5637.40it/s]

valid


 82%|████████▏ | 8219/9997 [00:02<00:00, 5490.14it/s]

valid


100%|██████████| 9997/9997 [00:02<00:00, 4073.93it/s]


6


 34%|███▎      | 3351/9997 [00:01<00:02, 3303.07it/s]

valid
valid


 56%|█████▌    | 5568/9997 [00:02<00:01, 4105.16it/s]

valid


 90%|█████████ | 9033/9997 [00:02<00:00, 5492.88it/s]

valid


100%|██████████| 9997/9997 [00:02<00:00, 3391.22it/s]


7


 13%|█▎        | 1252/9998 [00:00<00:02, 3939.99it/s]

valid
valid


 27%|██▋       | 2651/9998 [00:00<00:01, 4326.53it/s]

valid
valid
valid


 38%|███▊      | 3818/9998 [00:00<00:01, 4836.93it/s]

valid


 57%|█████▋    | 5679/9998 [00:01<00:00, 5666.58it/s]

valid
valid


 69%|██████▉   | 6884/9998 [00:01<00:00, 5550.42it/s]

valid
valid
valid


 74%|███████▍  | 7444/9998 [00:01<00:00, 4713.06it/s]

valid
valid


 84%|████████▍ | 8404/9998 [00:01<00:00, 4060.92it/s]

valid


100%|██████████| 9998/9998 [00:02<00:00, 4335.66it/s]


8


  5%|▍         | 472/9991 [00:00<00:03, 2696.05it/s]

valid


 31%|███▏      | 3141/9991 [00:01<00:02, 2712.25it/s]

valid
valid


 41%|████      | 4079/9991 [00:02<00:01, 3528.02it/s]

valid


 50%|█████     | 5009/9991 [00:02<00:01, 3662.47it/s]

valid


 70%|███████   | 7030/9991 [00:02<00:00, 4691.34it/s]

valid
valid


 88%|████████▊ | 8817/9991 [00:03<00:00, 4048.02it/s]

valid


100%|██████████| 9991/9991 [00:03<00:00, 2890.76it/s]


9


  8%|▊         | 825/9998 [00:00<00:02, 3534.21it/s]

valid


 60%|██████    | 6012/9998 [00:01<00:01, 3786.59it/s]

valid
valid


100%|██████████| 9998/9998 [00:02<00:00, 4152.39it/s]


valid


In [274]:
from tqdm import tqdm
import os
data1 = torch.load("/home/zjh/mr/pretrain/dataset/pretra.pth")
data2 = torch.load("/home/zjh/mr/pretrain/dataset/10000-20000.pth")

In [275]:
smi, nmr,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = data1[0]

In [276]:
nmr

tensor([ 117,   16,  -97,  150,  154,   11,  -79,  122,  137,  157,  154,  157,
         137,    8,  -81, -124,   17,   -7,   53,   57,   58,   53,  234,   23,
          29,   29,   29,   29,   28,   28,   30,   30,   29,   30,   30,   28,
          28,   24,   25,   24], dtype=torch.int32)

In [339]:
import bisect
import copy
from typing import Any, List, Dict
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader, random_split
from tokenizer import Tokenizer
import numpy as np

from utils import Smiles_to_adjoin, pad_mol_nmr, apply_mask


class Pretrain_Masked_AtomNmr_Dataset_3D(Dataset):
    def __init__(self,data = None, mol_fix_len=256):
        super().__init__()
        self.data = data
        self.mol_fix_len = mol_fix_len
        self.tokenizer = Tokenizer()


    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, index):


        # pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = [d.detach().numpy() for d in self.data[index][2:]]

        smi, nmr,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = self.data[index]
        nmr = np.array(nmr)
        atom_symbol_list, adjoin_matrix = Smiles_to_adjoin(smi, explicit_hydrogens=True,size=self.mol_fix_len - 1)

        nmr = nmr + 801

        atom_symbol_list_interim = self.tokenizer.add_special_atom(atom_symbol_list)
        nmr_interim = np.insert(nmr, 0,0)

        # 截断
        if len(atom_symbol_list) > self.mol_fix_len:
            atom_symbol_list_interim = atom_symbol_list_interim[:self.mol_fix_len]
            nmr_interim = nmr_interim[:self.mol_fix_len]

        raw_nmr = copy.copy(nmr_interim)
        raw_atom_symbol_list = copy.copy(atom_symbol_list_interim)
        raw_mol_ids_list = np.array(self.tokenizer.convert_atoms_to_ids(raw_atom_symbol_list), np.int64)


        masked_atom_symbol_list,masked_nmr,masked_flag = apply_mask(atom_symbol_list_interim, nmr_interim,self.tokenizer)


        masked_mol_ids_list = np.array(self.tokenizer.convert_atoms_to_ids(masked_atom_symbol_list), np.int64)
        masked_flag =  np.array(masked_flag,np.int64)

        adjoin_matrix_G = np.ones([len(atom_symbol_list_interim),len(atom_symbol_list_interim)])
        adjoin_matrix_G[1:, 1:] = adjoin_matrix


        return  adjoin_matrix_G, masked_mol_ids_list, masked_nmr, raw_nmr,masked_flag, raw_mol_ids_list,pos,\
                dist_i.long(),dist_j.long(),dist,angle_i.long(),angle_j.long(),angle_k.long(),angle,\
                torsion_k.long(),torsion_i.long(),torsion_j.long(),torsion_t.long(),torsion

    @staticmethod
    def collate_fn(batch: List[Any]) -> Dict[str, torch.Tensor]:
        adjoin_matrix_G, masked_mol_ids_list, masked_nmr, raw_nmr,masked_flag, raw_mol_ids_list,pos,dist_i,dist_j,dist,angle_i,angle_j,angle_k,angle,torsion_k,torsion_i,torsion_j,torsion_t,torsion = tuple(zip(*batch))

        batch_size = len(adjoin_matrix_G)
        # 该batch最大的图的shape,其余的图需要对齐到该shape
        padding_shape = np.max([seq.shape for seq in adjoin_matrix_G])
        shape = [batch_size] + [padding_shape] * 2
        dtype = adjoin_matrix_G[0].dtype

        array = np.full(shape, 0, dtype=dtype)
        for arr, matrix in zip(array, adjoin_matrix_G):
            arrslice = tuple(slice(dim) for dim in matrix.shape)
            arr[arrslice] = matrix
        adjoin_matrix_G = torch.from_numpy(array)

        # 将每个分子的nmr列表长度对齐（对齐到该batch中拥有最多原子的分子),
        # <padding>对应的nmr不会参与运算，设为任意值即可（[0,1801],这里设为0
        masked_mol_ids = torch.from_numpy(pad_mol_nmr(masked_mol_ids_list, 0)).long()
        atom_labels = torch.from_numpy(pad_mol_nmr(raw_mol_ids_list, 0)).long()
        masked_nmr = torch.from_numpy(pad_mol_nmr(masked_nmr, 0)).long()
        nmr_labels = torch.from_numpy(pad_mol_nmr(raw_nmr, 0)).long()
        masked_flag = torch.from_numpy(pad_mol_nmr(masked_flag, False))


        def index_helper(idx_tuple,padding_shape):
            # 第一个节点是global节点，需要跳过
            for i,idx in enumerate(idx_tuple):

                idx += 1
                idx += i * padding_shape


        for idx_tuple in [dist_i,dist_j,angle_i,angle_j,angle_k,torsion_k,torsion_i,torsion_j,torsion_t]:
            index_helper(idx_tuple,padding_shape)



        return {'adjoin_matrix': adjoin_matrix_G,
                'masked_mol_ids': masked_mol_ids,
                'masked_nmr': masked_nmr,
                'nmr_labels': nmr_labels,
                "atom_labels": atom_labels,
                "masked_flag": masked_flag,
                "pos":torch.concat(pos),
                "dist_i":torch.concat(dist_i) ,
                "dist_j":torch.concat(dist_j) ,
                "dist":torch.concat(dist),
                "angle_i":torch.concat(angle_i),
                "angle_j":torch.concat(angle_j) ,
                "angle_k":torch.concat(angle_k) ,
                "angle":torch.concat(angle),
                "torsion_k":torch.concat(torsion_k),
                "torsion_i":torch.concat(torsion_i),
                "torsion_j":torch.concat(torsion_j),
                "torsion_t":torch.concat(torsion_t),
                "torsion":torch.concat(torsion),
                }

In [385]:
a = torch.load("/home/zjh/mr/pretrain/dataset/pretrain_dataset_3d_2.pth")

In [387]:
torch.save(a[:10000],"/home/zjh/mr/pretrain/dataset/0-10000_test.pth")

In [340]:
dataset= Pretrain_Masked_AtomNmr_Dataset_3D(data=data1)

In [341]:
train_dataloader = DataLoader(dataset, batch_size=8,
                                  collate_fn=Pretrain_Masked_AtomNmr_Dataset_3D.collate_fn, shuffle=True,
                                  num_workers=0)
for batch in train_dataloader:
    break

In [342]:
from models import Pretrain_MR_BERT_3D

In [343]:
import yaml
from easydict import EasyDict

config_file = "/home/zjh/remote/mrbert/V1/config_pretrain_3D.yml"
with open(config_file, "r") as f:
    config = EasyDict(yaml.safe_load(f))

In [344]:
model = Pretrain_MR_BERT_3D(**config.bert)

In [345]:
batch_data = batch

In [346]:

adjoin_matrix = batch_data['adjoin_matrix']
masked_mol_ids = batch_data["masked_mol_ids"]
masked_nmr = batch_data["masked_nmr"]
nmr_labels = batch_data["nmr_labels"].float()
atom_labels = batch_data["atom_labels"]
masked_flag = batch_data["masked_flag"]

pos_raw = batch_data["pos"]
dist_i = batch_data["dist_i"]
dist_j = batch_data["dist_j"]
dist = batch_data["dist"]
angle_i = batch_data["angle_i"]
angle_j = batch_data["angle_j"]
angle_k = batch_data["angle_k"]
angle = batch_data["angle"]
torsion_k = batch_data["torsion_k"]
torsion_i = batch_data["torsion_i"]
torsion_j = batch_data["torsion_j"]
torsion_t = batch_data["torsion_t"]
torsion = batch_data["torsion"]

nmr, atom, pos, x_atom, x_nmr, x_pos, share = model(masked_mol_ids, masked_nmr, adjoin_matrix)


In [347]:
dist_i

tensor([  1,   1,   1,  ..., 830, 830, 830])

In [348]:
x_atom.reshape(-1,x_atom.shape[-1])[dist_i]

tensor([[-0.2586,  0.5305,  0.1180,  ...,  0.9983, -1.3127,  0.6645],
        [-0.2586,  0.5305,  0.1180,  ...,  0.9983, -1.3127,  0.6645],
        [-0.2586,  0.5305,  0.1180,  ...,  0.9983, -1.3127,  0.6645],
        ...,
        [-0.7826,  0.3751, -0.4737,  ..., -1.7343, -0.8775, -1.1144],
        [-0.7826,  0.3751, -0.4737,  ..., -1.7343, -0.8775, -1.1144],
        [-0.7826,  0.3751, -0.4737,  ..., -1.7343, -0.8775, -1.1144]],
       grad_fn=<IndexBackward0>)

In [356]:
from utils import get_torsion
from utils import get_dist
from utils import get_angle


In [357]:
from utils import get_angle


def compute_loss_dist(dist_labels, pos, dist_i, dist_j):
    pos = pos.reshape(-1,pos.shape[-1])
    dist_pred = get_dist(pos,dist_i,dist_j)
    loss = torch.nn.functional.mse_loss(dist_pred, dist_labels)
    return loss

def compute_loss_torsion(torsion_labels, pos, torsion_k, torsion_i, torsion_j, torsion_t):
    pos = pos.reshape(-1,pos.shape[-1])
    torsion_pred = get_torsion(pos,torsion_k, torsion_i, torsion_j, torsion_t)
    loss = torch.nn.functional.mse_loss(torsion_pred, torsion_labels)
    return loss

def compute_loss_angle(angle_labels, pos, angle_i, angle_j, angle_k):
    pos = pos.reshape(-1,pos.shape[-1])
    angle_pred = get_angle(pos,angle_i,angle_j,angle_k)
    loss = torch.nn.functional.mse_loss(angle_pred, angle_labels)

    return loss

In [46]:
# def get_dist_matrix(shape,dist_i,dist_j,dist):
#     res  = torch.zeros([shape]*2)
#     res[dist_i,dist_j] = dist
#     return res
#
# def get_torsion_matrix(shape,torsion_k,torsion_i,torsion_j,torsion_t,torsion):
#     res  = torch.zeros([shape]*4)
#     res[torsion_k,torsion_i,torsion_j,torsion_t] = torsion
#     return res
# def get_angle_matrix(shape,angle_i,angle_j,angle_k,angle):
#     res  = torch.zeros([shape]*3)
#     res[angle_i,angle_j,angle_k] = angle
#     return res

In [382]:
free = torch.load("/home/zjh/mr/downstream/dataset/regression/FreeSolv.pth")

In [383]:
len(free)

642

In [384]:
free

[['CN(C)C(=O)c1ccc(cc1)OC',
  array([148, 143, 148,  18, -54,  50,  53,  68,  24,  68,  53, 230, 129,
          29,  29,  29,  29,  29,  29,  24,  25,  25,  24,  28,  28,  28]),
  -11.01],
 ['CS(=O)(=O)Cl', array([133, 102,   5,   5, 218,  29,  29,  29]), -4.87],
 ['CC(C)C=C',
  array([165, 148, 165,  39,  68,  31,  31,  31,  29,  31,  31,  31,  26,
          26,  26]),
  1.83],
 ['CCc1cnccn1',
  array([170, 155,  24,  41, -97,  41,  41, -89,  31,  31,  31,  29,  29,
          23,  23,  23]),
  -5.45],
 ['CCCCCCCO',
  array([171, 160, 154, 156, 158, 151, 119, 295,  31,  31,  31,  30,  30,
          30,  30,  30,  30,  30,  30,  30,  30,  28,  28,  31]),
  -4.21],
 ['Cc1cc(cc(c1)O)C',
  array([164,  44,  57,  44,  72,  26,  72, 215, 164,  30,  30,  30,  24,
          25,  25,  28,  30,  30,  30]),
  -6.27],
 ['CC(C)C(C)C',
  array([166, 148, 166, 148, 166, 166,  31,  31,  31,  30,  31,  31,  31,
          30,  31,  31,  31,  31,  31,  31]),
  2.34],
 ['CCCC(C)(C)O',
  array([171, 164, 1